version: '3.8'
name: arches_her7-0
services:
    aher:
      container_name: aher7-0
      image: fargeo/aher7-0
      build:
        context: ..
        dockerfile: arches-her/Dockerfile
      command: run_arches
      volumes:
        - ../arches/:/web_root/arches
        - ./:/web_root/arches_her
      env_file:
        - ./docker/env_file.env
      ports:
        - 8004:8000
      stdin_open: true
      tty: true

networks:
  default:
    external: true
    name: arches7-0-dev

volumes:
    arches-log-aher7-0:
    arches-static-aher7-0:
